import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SideExploer from "@/components/exploer/SideExploer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-[100vh] overflow-hidden`}>
        <div className="min-w-[285px] h-full">
          <SideExploer />
        </div>
        <div className="w-full bg-[#2c2c2c] h-full p-3">
          {children}
        </div>
      </body>
    </html>
  );
}
